/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the kotlinx.serialization plugin for typed JSON serialization.
    alias(libs.plugins.kotlin.serialization)

    // Apply the shadow plugin for creating fat JARs.
    alias(libs.plugins.shadow)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // Use the PaperMC repository to fetch Minecraft server-related dependencies.
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    // Kotlin standard library
    implementation(kotlin("stdlib"))

    // Kotlinx Serialization JSON
    implementation(libs.kotlinx.serialization.json)

    // Paper API (do NOT bundle it inside your jar)
    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks {
    shadowJar {
        archiveClassifier.set("")
        // Relocate kotlinx.serialization to avoid conflicts with other plugins
        relocate("kotlinx.serialization", "me.dcnt.mc.verify.libs.kotlinx.serialization")
    }

    build {
        dependsOn(shadowJar)
    }
}
